version: '3.7'

services:
  redis:
    image: redis:6.0.9
    # change password when in production
    command: redis-server --requirepass redis_pass

  neo4j:
    build: ./neo4j
    env_file:
     - neo4j.env

  api:
    build: ./api
    ports:
      - 4001:4001
    env_file:
      - api.env
    environment:
      - NODE_ENV=dev
    links:
      - neo4j
    depends_on:
      - neo4j

  image_server:
    build: ./image_server
    environment:
      - EZ=GMT
    env_file:
      - image_server.env
    ports:
      - 8080:8080
    links:
      - neo4j
    depends_on:
      - neo4j
