export const mockedUsers = [
    {
        name: "kuba4",
        email: "Jacek@111",
        password: "lalala",
        age: 10,
        favoriteAlcoholName: "Harnas",
        favoriteAlcoholType: "VODKA",
        description: "test",
        genderPreference: "MALE",
        gender: "MALE",
        alcoholPreference: "VODKA",
        agePreferenceFrom: 3,
        agePreferenceTo: 7,
    },
    {
        name: "jacek4",
        email: "Jacek@1112",
        password: "lalala",
        age: 13,
        favoriteAlcoholName: "Harnas",
        favoriteAlcoholType: "VODKA",
        description: "test",
        genderPreference: "MALE",
        gender: "MALE",
        alcoholPreference: "VODKA",
        agePreferenceFrom: 23,
        agePreferenceTo: 25,
    },
    {
        name: "krzysiek2",
        email: "krzysiek@1113.com",
        password: "lalala",
        age: 15,
        favoriteAlcoholName: "Harnas",
        favoriteAlcoholType: "VODKA",
        description: "test",
        genderPreference: "MALE",
        gender: "MALE",
        alcoholPreference: "VODKA",
        agePreferenceFrom: 23,
        agePreferenceTo: 25,
    }
];